version: '3.9'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - '6379:6379'
    volumes:
      - ./redis-data:/data

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./uploads:/data

  api:
    build: ./apps/api
    env_file:
      - ./apps/api/.env.example
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/app
      REDIS_URL: redis://redis:6379
      JWT_SECRET: change-me
      DATA_ENCRYPTION_KEY: ${DATA_ENCRYPTION_KEY}
    depends_on:
      - postgres
      - redis
    ports:
      - '${API_PORT:-3001}:3001'

  web:
    build: ./apps/web
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://localhost:3001
    depends_on:
      - api
    ports:
      - '${WEB_PORT:-3000}:3000'
